<a href="https://colab.research.google.com/github/philsaurabh/Machine-Learning-Tutorials/blob/main/LDA_Glass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import libraries

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Import dataset

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/philsaurabh/Machine-Learning-Tutorials/main/glass.csv')

In [3]:
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [4]:
df.shape

(214, 10)

In [5]:
df.columns

Index(['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type'], dtype='object')

In [6]:
df.describe()

RI          Na          Mg  ...          Ba          Fe        Type
count  214.000000  214.000000  214.000000  ...  214.000000  214.000000  214.000000
mean     1.518365   13.407850    2.684533  ...    0.175047    0.057009    2.780374
std      0.003037    0.816604    1.442408  ...    0.497219    0.097439    2.103739
min      1.511150   10.730000    0.000000  ...    0.000000    0.000000    1.000000
25%      1.516523   12.907500    2.115000  ...    0.000000    0.000000    1.000000
50%      1.517680   13.300000    3.480000  ...    0.000000    0.000000    2.000000
75%      1.519157   13.825000    3.600000  ...    0.000000    0.100000    3.000000
max      1.533930   17.380000    4.490000  ...    3.150000    0.510000    7.000000

[8 rows x 10 columns]

# Data Cleaning and Preprocessing

In [7]:
df.isnull().sum().sum()

0

In [8]:
#df.drop('Unnamed: 0', axis=1, inplace=True)

In [9]:
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [10]:
df.isnull().sum().sum()

0

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, ConfusionMatrixDisplay, precision_score, recall_score, f1_score, classification_report, roc_curve, plot_roc_curve, auc, precision_recall_curve, plot_precision_recall_curve, average_precision_score
from sklearn.model_selection import cross_val_score

In [12]:
#df['target'] = df['target'].map({'Iris-setosa': 0, 'Iris-versicolor': 1,'Iris-virginica':2})
X = df.drop(columns = ['Type'])
y = df['Type'].values

In [13]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [14]:
Scaler = StandardScaler()
X = Scaler.fit_transform(X)

In [15]:
X

array([[ 0.87286765,  0.28495326,  1.25463857, ..., -0.14576634,
        -0.35287683, -0.5864509 ],
       [-0.24933347,  0.59181718,  0.63616803, ..., -0.79373376,
        -0.35287683, -0.5864509 ],
       [-0.72131806,  0.14993314,  0.60142249, ..., -0.82894938,
        -0.35287683, -0.5864509 ],
       ...,
       [ 0.75404635,  1.16872135, -1.86551055, ..., -0.36410319,
         2.95320036, -0.5864509 ],
       [-0.61239854,  1.19327046, -1.86551055, ..., -0.33593069,
         2.81208731, -0.5864509 ],
       [-0.41436305,  1.00915211, -1.86551055, ..., -0.23732695,
         3.01367739, -0.5864509 ]])

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((171, 9), (43, 9), (171,), (43,))

# SVM

In [18]:
from sklearn.model_selection import KFold

In [19]:
model = SVC()#KNeighborsClassifier()#SVC#RandomForestClassifier()#AdaBoostClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
score = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred,average="micro")
recall = recall_score(y_test, y_pred,average="micro")
cm = confusion_matrix(y_test, y_pred)
cv_score = cross_val_score(model, X_train, y_train, cv = 6)
kfold_validation=KFold(10)
k_fold =cross_val_score(model,X,y,cv=kfold_validation)
print ('Train score is', score)
print ('--')
print ('Precision score is ', precision)
print ('--')
print ('Recall Score is ', recall)
print ('--')
print ('Confusion Matrix\n\n', cm)
print ('--')
print ('CV score is', cv_score)
print(np.mean(cv_score))
print ('K fold score is', k_fold)
print(np.mean(k_fold))

Train score is 0.7209302325581395
--
Precision score is  0.7209302325581395
--
Recall Score is  0.7209302325581395
--
Confusion Matrix

 [[11  0  0  0  0  0]
 [ 4 10  0  0  0  0]
 [ 1  2  0  0  0  0]
 [ 0  2  0  2  0  0]
 [ 0  1  0  1  1  0]
 [ 0  1  0  0  0  7]]
--
CV score is [0.65517241 0.65517241 0.62068966 0.78571429 0.64285714 0.64285714]
0.6670771756978654
K fold score is [0.45454545 0.22727273 0.68181818 0.90909091 0.38095238 0.52380952
 0.47619048 0.04761905 0.23809524 0.9047619 ]
0.48441558441558435


# LDA

In [20]:
# Linear Discriminant Analysis
# Fit the model on the train data using LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
lda_pred = lda.fit(X_train, y_train).predict(X_test)

print(lda.means_)

# Find the accuracy of the test predictions vs the true classes
print("Training accuracy score: {:.3f}".format(lda.score(X_train,y_train)))
print("Test accuracy score: {:.3f}".format(lda.score(X_test,y_test)))

# Show the confusion matrix
cm_df = pd.DataFrame(confusion_matrix(y_test, lda_pred).T, index=model.classes_,columns=model.classes_)
cm_df.index.name = 'Predicted'
cm_df.columns.name = 'True'
print('\nConfusion table:\n', cm_df)

# Additional statistics
print('\n',classification_report(y_test, lda_pred))

[[ 0.10645911 -0.16691686  0.60778269 -0.56688049 -0.06810817 -0.06893347
  -0.13239634 -0.32246748 -0.01108048]
 [ 0.14066868 -0.32976446  0.21171208 -0.08853631 -0.13792552  0.02559469
   0.10983091 -0.23159764  0.31116632]
 [-0.09396991  0.02718757  0.59695521 -0.48164163 -0.36725668 -0.13708861
  -0.11306612 -0.33127789  0.05280805]
 [ 0.1115312  -0.81566533 -1.11423485  1.26164338 -0.42251297  1.29721657
   0.70410397  0.19365626 -0.00352511]
 [-0.09310547  1.10121129 -0.76407706 -0.1403459   0.52290365 -0.76391864
   0.43176984 -0.35287683 -0.5864509 ]
 [-0.35699562  1.24119968 -1.40786221  1.23200706  0.28657517 -0.08549314
  -0.3869095   1.80221704 -0.4639875 ]]
Training accuracy score: 0.649
Test accuracy score: 0.698

Confusion table:
 True        1  2  3  5  6  7
Predicted                   
1          10  6  3  0  0  0
2           1  8  0  1  0  0
3           0  0  0  0  0  0
5           0  0  0  3  0  0
6           0  0  0  0  2  1
7           0  0  0  0  1  7

           

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [21]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
df = pd.read_csv('https://raw.githubusercontent.com/philsaurabh/Machine-Learning-Tutorials/main/glass.csv')
#df['target'] = df['target'].map({'Iris-setosa': 0, 'Iris-versicolor': 1,'Iris-virginica':2})
X = df.drop(columns = ['Type']).values
y = df['Type'].values
# Standardizing the features
X = StandardScaler().fit_transform(X)
y=y.ravel()# For 1-D array of y elements
lda = LDA(n_components=3)# <= min(n_classes - 1, n_features)=(min(6,something))
reduced_data = lda.fit(X,y).transform(X)
principalDf = pd.DataFrame(data = reduced_data, columns = ['PC-1','PC-2','PC-3'])
# Adding lables
finalDf = pd.concat([principalDf, df[['Type']]], axis = 1)
X_f = finalDf.drop(columns = ['Type']).values
# Separating out the target
y_f = finalDf.loc[:,['Type']].values

In [22]:
finalDf.head()

PC-1      PC-2      PC-3  Type
0 -1.843629  1.070204  0.426325     1
1 -0.035910  1.007550  0.065493     1
2 -0.329413  0.482676  0.003256     1
3 -1.566863 -0.262982 -0.077932     1
4 -0.747609  0.644428  0.321360     1

# Additional(SVM+LDA)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X_f, y_f, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((171, 3), (43, 3), (171, 1), (43, 1))

In [24]:
import warnings
warnings.filterwarnings('ignore')
model = SVC()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
score = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred,average="micro")
recall = recall_score(y_test, y_pred,average="micro")
cm = confusion_matrix(y_test, y_pred)
cv_score = cross_val_score(model, X_train, y_train, cv = 6)
kfold_validation=KFold(10)
k_fold =cross_val_score(model,X,y,cv=kfold_validation)
print ('Train score is', score)
print ('--')
print ('Precision score is ', precision)
print ('--')
print ('Recall Score is ', recall)
print ('--')
print ('Confusion Matrix\n\n', cm)
print ('--')
print ('CV score is', cv_score)
print(np.mean(cv_score))
print ('K fold score is', k_fold)
print(np.mean(k_fold))

Train score is 0.7441860465116279
--
Precision score is  0.7441860465116279
--
Recall Score is  0.7441860465116279
--
Confusion Matrix

 [[ 9  2  0  0  0  0]
 [ 3 11  0  0  0  0]
 [ 2  1  0  0  0  0]
 [ 0  1  0  3  0  0]
 [ 0  2  0  0  1  0]
 [ 0  0  0  0  0  8]]
--
CV score is [0.62068966 0.51724138 0.51724138 0.67857143 0.64285714 0.53571429]
0.5853858784893268
K fold score is [0.45454545 0.22727273 0.68181818 0.90909091 0.38095238 0.52380952
 0.47619048 0.04761905 0.23809524 0.9047619 ]
0.48441558441558435
